### PR TITLE
[DOCUMENTATION:] Expand Readme

### PR DESCRIPTION
**Pull request by ByteOtter**
## Description

Expand README file to include preliminary information about installation and usage as well as a summary of Cobbler-TFTP.                                                                                                          

## Behaviour changes

No Changes.

## Category

This is related to a:

- [ ] Bugfix
- [ ] Feature
- [ ] Packaging
- [x] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [x] No tests required

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@ByteOtter could you please try - where reasonably possible - to shorten the line length to 120 characters.

**Comment by ByteOtter** [comment]
> @ByteOtter could you please try - where reasonably possible - to shorten the line length to 120 characters.

Sure will do :)

**Comment by ByteOtter** [comment]
I limited the line length, where applicable, to 120 characters and will clean up the git history now if there are no further objections :)

**Review by SchoolGuy — APPROVED** [review]
Thanks for the additions!

**Pull request merged**
